# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0024_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invited',
            field=models.ManyToManyField(blank=True, related_name='team_invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('Toggl', 'Toggl'), ('Github', 'Github'), ('Jira', 'Jira'), ('Asana', 'Asana'), ('Bitbucket', 'Bitbucket'), ('Trello', 'Trello'), ('Zendesk', 'Zendesk'), ('Quay', 'Quay'), ('Box', 'Box'), ('HipChat', 'HipChat'), ('__pycache__', '__pycache__'), ('Dropbox', 'Dropbox'), ('Slack', 'Slack')], max_length=50),
        ),
    ]
