# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-24 12:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0025_auto_20161002_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.RemoveField(
            model_name='errorlog',
            name='service',
        ),
        migrations.RemoveField(
            model_name='errorlog',
            name='team',
        ),
        migrations.RemoveField(
            model_name='errorlog',
            name='user',
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalinfos', to='team.Service'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalinfos', to='team.Team'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalinfos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('Toggl', 'Toggl'), ('Github', 'Github'), ('Jira', 'Jira'), ('Asana', 'Asana'), ('Bitbucket', 'Bitbucket'), ('Trello', 'Trello'), ('Zendesk', 'Zendesk'), ('Quay', 'Quay'), ('Box', 'Box'), ('HipChat', 'HipChat'), ('Dropbox', 'Dropbox'), ('Slack', 'Slack')], max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='admin',
            field=models.ManyToManyField(related_name='adminteams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='invited',
            field=models.ManyToManyField(blank=True, related_name='invitedteams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='memberteams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerteams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='teams', to='team.Service'),
        ),
        migrations.DeleteModel(
            name='ErrorLog',
        ),
        migrations.AddField(
            model_name='log',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errorlogs', to='team.Service'),
        ),
        migrations.AddField(
            model_name='log',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errorlogs', to='team.Team'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errorlogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
